C++/Java generator reads a packages class names more carefully to avoid FileNotFoundException in "mvn deploy"
Since deployment of JobScheduler v1.8-RC1, "mvn deploy" fails with
java.io.FileNotFoundException: JAR entry com/sos/scheduler/engine not found in /home/jenkins/.m2/repository/com/sos/scheduler/engine/engine-common/1.8.0/engine-common-1.8.0.jar
So we open the jar URL with root entry "/", and then the needless JarURLConnection.entryName is null.