@Ignore for Jenkins which does not like empty tests
Failed to read test report file C:\scheduler\workspace\020.engine.windows.x64.master.gimli\engine-plugins\engine-plugin-jetty\target\failsafe-reports\TEST-com.sos.scheduler.engine.plugins.webservice.services.EventsServiceIT.xml
org.dom4j.DocumentException: Invalid byte 2 of 3-byte UTF-8 sequence. Nested exception: Invalid byte 2 of 3-byte UTF-8 sequence.